backend:
  name: git-gateway
  branch: main

media_folder: 'static/assets'
public_folder: '/assets'

editor:
  preview: false

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: home
        label: Tatreal
        file: content/pages/home.yml
        fields:
          - name: docTitle
            widget: string
          - name: header
            widget: object
            fields:
              - name: logo
                widget: image
              - name: nav
                widget: object
                fields:
                  - name: item1
                    widget: string
                  - name: item2
                    widget: string
                  - name: item3
                    widget: string
              - name: button
                widget: string
          - name: main
            widget: object
            fields:
              - name: music
                widget: object
                fields:
                  - name: spotify
                    widget: string
                  - name: itunes
                    widget: string
                  - name: bandcamp
                    widget: string
                  - name: deezer
                    widget: string
                  - name: youtube
                    widget: string
                  - name: soundcloud
                    widget: string
              - name: social
                widget: object
                fields:
                  - name: discord
                    widget: string
                  - name: reddit
                    widget: string
                  - name: instagram
                    widget: string
                  - name: facebook
                    widget: string
                  - name: twitter
                    widget: string
                  - name: twitterlogo
                    widget: string
              - name: 'aboutme'
                label: 'Slides'
                widget: 'list'
                fields:
                  - name: 'text'
                    label: 'Text'
                    widget: 'string'
                  - name: 'longText'
                    label: 'Long Text'
                    widget: 'markdown'
                  - name: 'backgroundImage'
                    label: 'Background Image'
                    widget: 'image'
